name: film
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_sliders: ^19.4.41

  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_html: ^2.2.1
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.9.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  bloc: ^8.0.3
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.6
  path_provider: ^2.0.10
  path: ^1.8.0

flutter_icons:
  #for ios
  ios: true
  image_path: 'assets/ic_launcher_film.png'
  remove_alpha_ios: true
  #for android
  android: true
  adaptive_icon_foreground: 'assets/ic_launcher_film.png'
  adaptive_icon_background: '#FFFFFF'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.6
  drift_dev: ^1.5.2
  build_runner: ^2.1.10

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

